config/routes.rb
Rails.application.routes.draw do
  get 'arrivals/index_all', to: 'arrivals#index_all'
  get 'answers/index'
  get 'answers/show'
  get 'answers/new'
  get 'answers/edit'
  root 'sessions#new'

  # LINEログイン
  get 'line_login_api/login', to: 'line_login_api#login'
  get 'line_login_api/callback', to: 'line_login_api#callback'
  
  # ログイン機能
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :users
  resources :departments
  resources :manufacturers
  resources :suppliers
  resources :paints
  resources :orders, shallow: true do
    resources :answers # :shallowオプションを使うことで、ルーティングの記述を複雑にせず、かつ深いネストを作らない。
    resources :arrivals
  end
  resources :inventories
  resources :all_inventories
  resources :withdraws
  resources :stocks, only: [:index, :show]
end

app/models/all_inventory.rb
class AllInventory < ApplicationRecord
  belongs_to :paint
  with_options presence: true do
    validates :paint_id
    validates :inventory_at
  end
  # 塗料棚卸を登録する際、その塗料、年月の組み合わせが一意であること。
  validates :paint_id, uniqueness: {scope: [:inventory_at]}
  validate :no_future_registration_possible
  
  def no_future_registration_possible
    if inventory_at >= Date.current.beginning_of_month
      errors.add('今月以降の棚卸は確定できません。')
    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  # include AnswersHelper
  belongs_to :order, class_name: 'Order',foreign_key: 'order_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/arrival.rb
class Arrival < ApplicationRecord
  belongs_to :order
  belongs_to :user
  with_options presence: true do
    validates :order_id
    validates :user_id
    validates :arrival_at
    validates :quantity
  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :users
  has_many :inventorys
  has_many :withdraws, foreign_key: "reference_id"
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  belongs_to :editor, class_name: "User", foreign_key: "editor_id"
  belongs_to :department
  belongs_to :paint
    with_options presence: true do
    validates :inventory_at
    validates :quantity
  end
  # 塗料棚卸を登録する際、その塗料、部署、年月の組み合わせが一意であること。
  validates :paint_id, uniqueness: {scope: [:department_id, :inventory_at]}
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :paint
  belongs_to :user
  belongs_to :registerer, class_name: "User", foreign_key: "registerer_id"
  belongs_to :editor, class_name: "User", foreign_key: "editor_id"
  has_many :answers, dependent: :destroy
  has_many :arrivals, dependent: :destroy
  with_options presence: true do
    validates :paint_id
    validates :user_id
    validates :order_on
    validates :quantity
  end
end

app/models/paint.rb
class Paint < ApplicationRecord
  belongs_to :manufacturer
  has_many :orders, dependent: :destroy
  has_many :inventories
  has_many :all_inventories
  has_many :withdraws, foreign_key: "reference_id"
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :department, foreign_key: "department_id", optional: true
  has_many :orders, foreign_key: "reference_id"
  has_many :orders, foreign_key: "registerer_id"
  has_many :orders, foreign_key: "editor_id"
  has_many :arrivals, foreign_key: "arrival_id"
  has_many :inventorys, foreign_key: "reference_id"
  has_many :inventorys, foreign_key: "editor_id"
  has_many :withdraws, foreign_key: "reference_id"
  with_options presence: true do
    validates :name
    validates :department_id
  end
  has_secure_password
  validates :password, presence: true, length: { minimum: 4 }, allow_nil: true
end

app/models/withdraw.rb
class Withdraw < ApplicationRecord
  belongs_to :user
  belongs_to :department
  belongs_to :paint
end

app/controllers/paints_controller.rb
class PaintsController < ApplicationController
  before_action :set_paint, only: [:show, :edit, :update, :destroy]
  before_action :set_manufacturers, only: [:new, :create, :edit, :update]

  def index
    @paints = Paint.order(:discontinue).order(:name)
  end

  def show
  end

  def new
    @paint = Paint.new
  end

  def create
    @paint = Paint.new(paint_params)
    if @paint.save
      flash[:success] = '新規作成に成功しました。'
      redirect_to @paint
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @paint.update(paint_params)
      flash[:success] = '更新に成功しました。'
      redirect_to @paint
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @paint.destroy
    flash[:success] = "#{@paint.name}を削除しました。"
    redirect_to paints_path, status: :see_other
  end
  

  private
    def paint_params
      params.require(:paint).permit(:name, :manufacturer_id, :unit_price, :ordering_point, :main_ingredient, :warranty, :discontinue)
    end

    # beforeフィルター
    def set_paint
      @paint = Paint.find(params[:id])
    end

    def set_manufacturers
      @manufacturers = Manufacturer.order(:name)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper

# 納入予定量回答の総量に対しての注文残量[kg]
  def answers_helper_residual(answer)
    answers = answer.order.answers
    answers_total_quantity = 0
    answers.each do |ans|
      answers_total_quantity += ans.quantity if ans.quantity.present?
    end
    if answers_total_quantity == 0
      return answer.order.quantity
    else
      return answer.order.quantity - answers_total_quantity
    end
  end

  def answer_title(order)
    base_title = "回答一覧"
    if order.nil?
      base_title
    else
      "発注に対する" + base_title
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_name = "")
    base_title = "StockControlApp"
    if page_name.empty?
      base_title
    else
      page_name + " | " + base_title
    end
  end
end

app/helpers/arrivals_helper.rb
module ArrivalsHelper
  
  # 入荷量の総量に対しての注文残量[kg]
  def arrivals_helper_residual(order)
    arrivals = order.arrivals
    arrivals_total_quantity = 0
    if arrivals.nil?
      arrivals_total_quantity
    else
      arrivals.each do |arri|
        arrivals_total_quantity += arri.quantity if arri.quantity.present?
      end
    end
    order.quantity - arrivals_total_quantity
  end
end

app/helpers/orders_helper.rb
module OrdersHelper

  # 納入予定量回答の総量に対しての注文残量[kg]
  def orders_helper_residual(order)
    answers = order.answers
    answers_total_quantity = 0
    if answers.nil?
      answers_total_quantity
    else
      answers.each do |ans|
        answers_total_quantity += ans.quantity if ans.quantity.present?
      end
      order.quantity - answers_total_quantity
    end
  end

end

app/helpers/paints_helper.rb
module PaintsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 引数に渡されたユーザーオブジェクトでログインします。
  def log_in(user)
    session[:user_id] = user.id
  end

  # セッションと@current_userを破棄します
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # 現在ログイン中のユーザーがいる場合オブジェクトを返します。
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # 現在ログイン中のユーザーがいればtrue、そうでなければfalseを返します。
  def logged_in?
    !current_user.nil?
  end

end

app/helpers/stocks_helper.rb
module StocksHelper

  def beginning_stocks(paint)
    AllInventory.find_by(inventory_at: @last_month, paint_id: paint.id)
  end

  def monthly_withdraws_quantity(paint)
    @monthly_withdraws = Withdraw.where(withdraw_at: @first_day..@day, paint_id: paint.id)
    @withdraws_quantity = 0
    @monthly_withdraws.each do |withdraw|
      @withdraws_quantity += withdraw.quantity
    end
    return @withdraws_quantity
  end
  
  def monthly_arrivals_quantity(paint)
    @monthly_arrivals = Arrival.joins(:order).where(arrival_at: @first_day..@day).where(orders: {paint_id: paint.id})

    @arrivals_quantity = 0.0
    @monthly_arrivals.each do |arrival|
      @arrivals_quantity += arrival.quantity
    end
    return @arrivals_quantity
  end

  def stock(paint)
    beginning_stocks(paint).quantity + @arrivals_quantity - @withdraws_quantity
  end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/withdraws_helper.rb
module WithdrawsHelper
end

app/views/paints/_form.html.erb
<%= form_with model: paint do |form| %>
 <%= render 'shared/error_messages_of_paints' %> 

  <%= form.label :name, class: "form-label m-1" %><br>
  <%= form.text_field :name, class: "form-control my-1" %>

  <%= form.label :manufacturer, class: "form-label m-1" %>
  <% if @paint.manufacturer_id.present? %>
    <%= form.collection_select :manufacturer_id, @manufacturers, :id, :name, { include_blank: "選択してください", selected: @paint.manufacturer_id }, class: 'form-control my-1' %>
  <% else %>
    <%= form.collection_select :manufacturer_id, @manufacturers, :id, :name, { include_blank: "選択してください", selected:"" }, class: 'form-control my-1' %>
  <% end %>

  <%= form.label :unit_price, class: "form-label m-1" %><br>
  <%= form.number_field :unit_price, min: "0", step: "0.001", class: 'form-control my-1' %>

  <%= form.label :ordering_point, class: "form-label m-1" %><br>
  <%= form.number_field :ordering_point, min: "0", step: "0.001", class: "form-control my-1" %>

  <%= form.label :main_ingredient, class: "form-label m-1" %><br>
  <%= form.text_field :main_ingredient, class: "form-control my-1" %>

  <%= form.label :warranty, class: "form-label m-1" %><br>
  <%= form.number_field :warranty, min: "1", class: 'form-control my-1' %>

  <%= form.label :discontinue, class: "form-check-label m-1" %><br>
  <%= form.check_box :discontinue, class: 'form-check-input my-1 p-3' %>

  <div class="d-grid gap-2">
    <%= form.submit yield(:btn_text), class: "btn btn-primary mt-1" %>
    <%= link_to "戻る", :back, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/paints/edit.html.erb
<% provide(:title, "塗料情報更新") %>
<% provide(:btn_text, '更新') %>

<div class="text-center">
  <h1>塗料情報の更新</h1>
</div>

<div class="row justify-content-center">
  <div class="col-5">
    <%= render "form", paint: @paint %>
  </div>
</div>

app/views/paints/index.html.erb
<% provide(:title, "塗料一覧") %>

<div class="text-center">
  <h1>塗料一覧</h1>
</div>
<div>
  <h3>塗料登録数：<%= @paints.present? ? "#{@paints.where(discontinue: false).count}" : "0" %>件（現行品）</h3>
  <h6 class="text-danger"><%= "＊廃盤塗料は赤色(#{@paints.where(discontinue: true).count}件)" %></h6>
  <%= link_to "塗料登録", new_paint_path, class: "btn btn-primary m-1" %>
    <% if @paints.present? %>
      <div class="row justify-content-center text-center">
        <div class="col-8">
          <table id ="fav-table" class="table">
            <thead>
              <tr>
                <th scope="col"><%= Paint.human_attribute_name("name") %></th>
                <th scope="col"><%= Paint.human_attribute_name("unit_price") %></th>
                <th scope="col"><%= Paint.human_attribute_name("ordering_point") %></th>
                <th scope="col"><%= Paint.human_attribute_name("main_ingredient") %></th>
                <th scope="col"><%= Paint.human_attribute_name("warranty") %></th>
              </tr>
            </thead>
            <tbody>
            <% @paints.each do |paint| %>
              <% if paint.discontinue%>
                <tr class="align-middle text-danger">
                  <td><%= link_to paint.name, paint, class: "link-danger" %></td>
                  <td><%= paint.unit_price %></td>
                  <td><%= paint.ordering_point %></td>
                  <td><%= paint.main_ingredient %></td>
                  <td><%= paint.warranty %></td>
                  <td><%= link_to "編集", edit_paint_path(paint), class: "btn btn-sm btn-success" %></td>
                  <td><%= link_to "削除", paint_path(paint), data: {
                    turbo_method: :delete,
                      turbo_confirm: "本当に削除しますか？"
                    }, class: "btn btn-sm btn-danger" %></td>
                </tr>
              <% else %>
                <tr class="align-middle">
                  <td><%= link_to paint.name, paint %></td>
                  <td><%= paint.unit_price %></td>
                  <td><%= paint.ordering_point %></td>
                  <td><%= paint.main_ingredient %></td>
                  <td><%= paint.warranty %></td>
                  <td><%= link_to "編集", edit_paint_path(paint), class: "btn btn-sm btn-success" %></td>
                  <td><%= link_to "削除", paint_path(paint), data: {
                    turbo_method: :delete,
                      turbo_confirm: "本当に削除しますか？"
                    }, class: "btn btn-sm btn-danger" %></td>
                </tr>
              <% end %>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
</div>

app/views/paints/new.html.erb
<% provide(:title, "塗料登録") %>
<% provide(:btn_text, '新規作成') %>

<div class="text-center">
  <h1>塗料登録</h1>
</div>

<div class="row justify-content-center">
  <div class="col-5">
    <%= render "form", paint: @paint %>
  </div>
</div>

app/views/paints/show.html.erb
<% provide(:title, @paint.name) %>

<div class="text-center">
  <% if @paint.discontinue %>
    <h1 class="text-danger">塗料情報（廃盤）</h1>
  <% else %>
    <h1>塗料情報</h1>
  <% end %>
</div>

<div class="row justify-content-center text-center">
  <div class="col-4">
    <table class="table">
      <tbody>
        <tr>
          <td scope="row"><%= Paint.human_attribute_name("name") %></td>
          <td><%= @paint.name %></td>
        </tr>
        <tr>
          <td scope="row"><%= Paint.human_attribute_name("unit_price") %></td>
          <td><%= @paint.unit_price %></td>
        </tr>
        <tr>
          <td scope="row"><%= Paint.human_attribute_name("ordering_point") %></td>
          <td><%= @paint.ordering_point %></td>
        </tr>
        <tr>
          <td scope="row"><%= Paint.human_attribute_name("main_ingredient") %></td>
          <td><%= @paint.main_ingredient %></td>
        </tr>
        <tr>
          <td scope="row"><%= Paint.human_attribute_name("warranty") %></td>
          <td><%= @paint.warranty %></td>
        </tr>
        <tr>
          <td scope="row">廃盤／現行</td>
          <td><%= @paint.discontinue ? '廃盤' : '現行' %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>


<ul>
  <li><%= link_to "編集", edit_paint_path(@paint), class: "btn btn-success m-1" %></li>
  <li><%= link_to "削除", paint_path(@paint), data: {
                    turbo_method: :delete,
                    turbo_confirm: "本当に削除しますか？"
                  }, class: "btn btn-danger m-1" %></li>
  <li><%= link_to "一覧に戻る", paints_path, class: "btn btn-secondary m-1" %></li>

</ul>