config/routes.rb
Rails.application.routes.draw do
  get 'arrivals/index_all', to: 'arrivals#index_all'
  get 'answers/index'
  get 'answers/show'
  get 'answers/new'
  get 'answers/edit'
  root 'sessions#new'

  # LINEログイン
  get 'line_login_api/login', to: 'line_login_api#login'
  get 'line_login_api/callback', to: 'line_login_api#callback'
  
  # ログイン機能
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :users
  resources :departments
  resources :manufacturers
  resources :suppliers
  resources :paints
  resources :orders, shallow: true do
    resources :answers # :shallowオプションを使うことで、ルーティングの記述を複雑にせず、かつ深いネストを作らない。
    resources :arrivals
  end
  resources :inventories
  resources :all_inventories
  resources :withdraws
  resources :stocks, only: [:index, :show]
end

app/models/arrival.rb
class Arrival < ApplicationRecord
  belongs_to :order
  belongs_to :user
  with_options presence: true do
    validates :order_id
    validates :user_id
    validates :arrival_at
    validates :quantity
  end
end

app/controllers/arrivals_controller.rb
class ArrivalsController < ApplicationController

  # 発注に対する入荷情報一覧ページ
  def index
    @order = Order.find(params[:order_id])
    @arrivals = @order.arrivals
  end

  def index_all
    @arrivals = Arrival.all
  end
  
  def show
  end

  def new
    @users = User.all
    @paints = Paint.all
    @order = Order.find(params[:order_id])
    @answers = @order.answers
    @arrival = Arrival.new(order_id: params[:order_id])
  end

  def create
    @users = User.all
    @order = Order.find(params[:order_id])
    @arrival = @order.arrivals.build(arrival_params)
    if @arrival.save
      flash[:success] = '入荷登録しました。'
      redirect_to orders_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @users = User.all
    @paints = Paint.all
    @arrival = Arrival.find(params[:id])
    @order = @arrival.order
    # @answers = @order.answers
    # @arrival = Arrival.new(order_id: params[:order_id])
  end

  def update
    @arrival = Arrival.find(params[:id])
    if @arrival.update(arrival_params)
      flash[:success] = '更新に成功しました。'
      redirect_to order_arrivals_path(order_id: @arrival.order.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @arrival = Arrival.find(params[:id])
    @arrival.destroy
    flash[:success] = "品番：#{@arrival.order.paint.name}, 数量：#{@arrival.quantity}kg, 
                      納入日：#{@arrival.arrival_at.strftime("%Y/%m/%d") }　を削除しました。"
    redirect_to order_arrivals_url(order_id: @arrival.order.id), status: :see_other
  end
  
  
  private
    def arrival_params
      params.require(:arrival).permit(:order_id, :user_id, :arrival_at, :lot_number, :quantity)
    end
end

app/helpers/arrivals_helper.rb
module ArrivalsHelper
  
  # 入荷量の総量に対しての注文残量[kg]
  def arrivals_helper_residual(order)
    arrivals = order.arrivals
    arrivals_total_quantity = 0
    if arrivals.nil?
      arrivals_total_quantity
    else
      arrivals.each do |arri|
        arrivals_total_quantity += arri.quantity if arri.quantity.present?
      end
    end
    order.quantity - arrivals_total_quantity
  end
end

app/views/arrivals/_form.html.erb
<%= form_with(model:[order,arrival]) do |form| %>
  <%= render 'shared/error_messages_of_arrivals' %> 

  <%= form.label "塗料", class: "form-label m-1" %>
  <%# 塗料名の入力フォームは表示のみのダミー。実際にはorder_idに@order.idを入れている。 %>
  <%= form.text_field :order, value: arrival.order.paint.name , disabled: true, class: 'form-control my-1'%>
  <%= hidden_field_tag :order, arrival.order.id %>

  <%= form.label :user, class: "form-label m-1" %>
  <%= form.collection_select :user_id, @users, :id, :name, { selected: current_user.id }, class: 'form-control my-1'%>

  <%= form.label :arrival_at, class: "form-label m-1" %>
  <%= form.date_field :arrival_at, value: Date.today, class: 'form-control my-1'%>

  <%= form.label :lot_number, class: "form-label m-1" %>
  <%= form.text_field :lot_number, class: "form-control my-1" %>

  <%= form.label :quantity, class: "form-label m-1" %><br>
  <%= form.number_field :quantity, min: "0.001", max: arrivals_helper_residual(arrival.order), value: arrivals_helper_residual(@order), step: "0.001", class: "form-control my-1" %>

  <div class="d-grid gap-2">
    <%= form.submit yield(:btn_text), class: "btn btn-primary my-1" %>
  </div>
<% end %>

app/views/arrivals/edit.html.erb
<% provide(:title, "入荷情報編集") %>
<% provide(:btn_text, '更新') %>

<div class="text-center">
  <h1>入荷情報編集</h1>
</div>

<div class="row justify-content-center">
  <div class="col-3">
    <h3>発注情報</h3>
    <p class="fw-bold"><%= "発注量トータル : #{@total}" %></p>
    <p><%= "#{Order.human_attribute_name("order_on")} : #{@order.order_on.strftime("%Y / %m / %d")}" %></p>
    <p class="fw-bold"><%= "#{Order.human_attribute_name("paint")} : #{@order.paint.name}" %></p>
    <p><%= "#{Order.human_attribute_name("quantity")} : #{@order.quantity}" %></p>
    <p class="fw-bold"><%= "残量[kg] : #{arrivals_helper_residual(@order)}" %></p>
    <p class="fw-bold"><%= "#{Order.human_attribute_name("desired_on")} : #{@order.desired_on.strftime("%Y / %m / %d")}" %></p>
    <p><%= "#{Order.human_attribute_name("note")} : #{@order.note.present? ? @order.note : "-"}" %></p>
  </div>
  <div class="col-5">
    <%= render "form", order: nil , arrival: @arrival %>
  </div>
</div>

app/views/arrivals/index.html.erb
<% provide(:title, "入荷一覧") %>

<%# とりあえずコピペしただけ。これから中身整える %>
<div class="row justify-content-center text-center">
  <div class="col-12">
    <h1>入荷一覧</h1>
    <% if @order.present? %>
      <h3>発注情報</h3>
      <td><%= link_to "編集", edit_order_path(@order), class: "btn btn-sm btn-success" %></td>
      <td><%= link_to "削除", order_path(@order), data: {turbo_method: :delete,
                                                        turbo_confirm: "本当に削除しますか？"
                                                      }, class: "btn btn-sm btn-danger" %></td>
      <table class="table my-3">
        <thead>
          <tr>
            <th scope="col"><%= Order.human_attribute_name("paint") %></th>
            <th scope="col"><%= Order.human_attribute_name("order_on") %></th>
            <th scope="col"><%= Order.human_attribute_name("desired_on") %></th>
            <th scope="col"><%= Order.human_attribute_name("quantity") %></th>
            <th scope="col"><%= Order.human_attribute_name("note") %></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @order.paint.name %></td>
            <td><%= @order.order_on.strftime("%Y / %m / %d") %></td>
            <td><%= @order.desired_on.strftime("%Y / %m / %d") %></td>
            <td><%= @order.quantity %></td>
            <td><%= @order.note %></td>
          </tr>
        </tbody>
      <table>
    <% end %>

    <% if @arrivals.present? %>
      <h1>入荷一覧</h1>
      <% if arrivals_helper_residual(@order).to_i != 0 %>
        <td><%= link_to "新規入荷登録", new_order_arrival_path(@order), class: "btn btn-sm btn-primary" %></td>
      <% else %>
        <td><%= link_to "完納されています", new_order_arrival_path(@order), class: "btn btn-sm btn-primary disabled" %></td>
      <% end %>
      <table id ="fav-table" class="table my-3">
        <thead>
          <tr>
            <th scope="col"><%= Order.human_attribute_name("order_on") %></th>
            <th scope="col"><%= Paint.human_attribute_name("name") %></th>
            <th scope="col"><%= Order.human_attribute_name("quantity") %></th>
            <th scope="col"><%= Arrival.human_attribute_name("arrival_at") %></th>
            <th scope="col"><%= Arrival.human_attribute_name("lot_number") %></th>
            <th scope="col"><%= Arrival.human_attribute_name("quantity") %></th>
          </tr>
        </thead>
        <tbody>
          <% @arrivals.each do |arrival| %>
            <tr class="align-middle">
              <td><%= arrival.order.order_on.strftime("%Y / %m / %d") %></td>
              <td><%= link_to arrival.order.paint.name, order_path(id: arrival.order.id) %></td>
              <td><%= arrival.order.quantity %></td>
              <td><%= arrival.arrival_at.strftime("%Y / %m / %d") %></td>
              <td><%= arrival.lot_number %></td>
              <td><%= arrival.quantity %></td>
              <td><%= link_to "編集",edit_arrival_path(arrival), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "削除", arrival_path(arrival), data: {turbo_method: :delete,
                                                                  turbo_confirm: "本当に削除しますか？"
                                                                  }, class: "btn btn-sm btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      <table>
    <% end %>
  </div>
</div>

app/views/arrivals/index_all.html.erb
<% provide(:title, "入荷一覧") %>

<div class="row justify-content-center text-center">
  <div class="col-12">
    <h1>入荷一覧</h1>
    <% if @arrivals.present? %>
      <table id ="fav-table" class="table my-3">
        <thead>
          <tr>
            <th scope="col"><%= Order.human_attribute_name("order_on") %></th>
            <th scope="col"><%= Paint.human_attribute_name("name") %></th>
            <th scope="col"><%= Order.human_attribute_name("quantity") %></th>
            <th scope="col"><%= Arrival.human_attribute_name("arrival_at") %></th>
            <th scope="col"><%= Arrival.human_attribute_name("lot_number") %></th>
            <th scope="col"><%= Arrival.human_attribute_name("quantity") %></th>
          </tr>
        </thead>
        <tbody>
          <% @arrivals.each do |arrival| %>
            <tr class="align-middle">
              <td><%= arrival.order.order_on.strftime("%Y / %m / %d") %></td>
              <td><%= link_to arrival.order.paint.name, order_arrivals_path(arrival.order) %></td>
              <td><%= arrival.order.quantity %></td>
              <td><%= arrival.arrival_at.strftime("%Y / %m / %d") %></td>
              <td><%= arrival.lot_number %></td>
              <td><%= arrival.quantity %></td>
              <td><%= link_to "編集",edit_arrival_path(arrival), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "削除", arrival_path(arrival), data: {turbo_method: :delete,
                                                                  turbo_confirm: "本当に削除しますか？"
                                                                  }, class: "btn btn-sm btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      <table>
    <% end %>
  </div>
</div>

app/views/arrivals/new.html.erb
<% provide(:title, "入荷登録") %>
<% provide(:btn_text, '新規登録') %>

<div class="text-center">
  <h1>入荷登録</h1>
</div>

<div class="row justify-content-center">
  <div class="col-3">
    <h3>発注情報</h3>
    <p class="fw-bold"><%= "発注量トータル : #{@total}" %></p>
    <p><%= "#{Order.human_attribute_name("order_on")} : #{@order.order_on.strftime("%Y / %m / %d")}" %></p>
    <p class="fw-bold"><%= "#{Order.human_attribute_name("paint")} : #{@order.paint.name}" %></p>
    <p><%= "#{Order.human_attribute_name("quantity")} : #{@order.quantity}" %></p>
    <p class="fw-bold"><%= "残量[kg] : #{arrivals_helper_residual(@order)}" %></p>
    <p class="fw-bold"><%= "#{Order.human_attribute_name("desired_on")} : #{@order.desired_on.strftime("%Y / %m / %d")}" %></p>
    <p><%= "#{Order.human_attribute_name("note")} : #{@order.note.present? ? @order.note : "-"}" %></p>
  </div>
  <div class="col-5">
    <%= render "form", order: @order , arrival: @arrival %>
  </div>
</div>

app/views/arrivals/show.html.erb
<h1>Arrivals#show</h1>
<p>Find me in app/views/arrivals/show.html.erb</p>