config/routes.rb
Rails.application.routes.draw do
  get 'arrivals/index_all', to: 'arrivals#index_all'
  get 'answers/index'
  get 'answers/show'
  get 'answers/new'
  get 'answers/edit'
  root 'sessions#new'

  # LINEログイン
  get 'line_login_api/login', to: 'line_login_api#login'
  get 'line_login_api/callback', to: 'line_login_api#callback'
  
  # ログイン機能
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :users
  resources :departments
  resources :manufacturers
  resources :suppliers
  resources :paints
  resources :orders, shallow: true do
    resources :answers # :shallowオプションを使うことで、ルーティングの記述を複雑にせず、かつ深いネストを作らない。
    resources :arrivals
  end
  resources :inventories
  resources :all_inventories
  resources :withdraws
  resources :stocks, only: [:index, :show]
end

app/models/answer.rb
class Answer < ApplicationRecord
  # include AnswersHelper
  belongs_to :order, class_name: 'Order',foreign_key: 'order_id'
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index

    # 発注情報一覧から、特定の発注の回答一覧を確認するときに発注情報を保持する。
    @order = Order.find(params["order_id"]) if params["order_id"].present?
    # 特定の発注情報を保持していない（ヘッダーから回答一覧ページに遷移する）時、
    # 発注情報を特定せずに全ての回答を回答一覧に表示させる。
    # 特定の回答を保持している時はそれに対する回答のみを表示させる。
    if @order.nil?
      @answers = Answer.all.order(scheduled_at: :ASC)
    else
      @answers = Answer.where(order_id: @order.id).order(scheduled_at: :ASC)
    end
  end

  def show
  end

  def new
    @users = User.all
    @paints = Paint.all
    @answer = Answer.new(order_id: params[:order_id])
    @order = @answer.order
    @total = 0
    @answer.order.answers.each do |answer|
      @total =+ answer.quantity
    end
  end

  def create
    @order = Order.find(params[:order_id])
    @answer = @order.answers.build(answer_params)
    if @answer.save
      flash[:success] = '回答登録しました。'
      redirect_to orders_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @answer = Answer.find(params[:id])
    @paints = Paint.all
  end

  def update
    @answer = Answer.find(params[:id])
    @answers = Answer.all.order(scheduled_at: :ASC)
    if @answer.update(answer_params)
      @answer.save
      flash[:success] = '更新に成功しました。'
      redirect_to order_answers_url(order_id: @answer.order.id)
    else
      # @answer = Answer.find(params[:id])
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    flash[:success] = "品番：#{@answer.order.paint.name}, 数量：#{@answer.quantity}kg, 
                      納入予定日：#{@answer.scheduled_at.strftime("%Y/%m/%d") }　を削除しました。"
    redirect_to order_answers_url(order_id: @answer.order.id), status: :see_other
  end

  private
    def answer_params
      params.require(:answer).permit(:order_id, :scheduled_at, :quantity, :note)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper

# 納入予定量回答の総量に対しての注文残量[kg]
  def answers_helper_residual(answer)
    answers = answer.order.answers
    answers_total_quantity = 0
    answers.each do |ans|
      answers_total_quantity += ans.quantity if ans.quantity.present?
    end
    if answers_total_quantity == 0
      return answer.order.quantity
    else
      return answer.order.quantity - answers_total_quantity
    end
  end

  def answer_title(order)
    base_title = "回答一覧"
    if order.nil?
      base_title
    else
      "発注に対する" + base_title
    end
  end
end

app/views/answers/_form.html.erb
<%= form_with(model:[order,answer]) do |form| %>
  <%= form.label "塗料", class: "form-label m-1" %>
  <%= form.collection_select :order, @paints, :id, :name, { selected: answer.order.paint.id }, disabled: true, class: 'form-control my-1'%>

  <%= form.label :quantity, class: "form-label m-1" %><br>
  <% if params["action"] == "new" %>
    <%= form.number_field :quantity, min: "0.001", max: answers_helper_residual(answer).to_f, step: "0.001", value: answers_helper_residual(answer), class: "form-control my-1" %>
  <% else %>
    <%= form.number_field :quantity, min: "0.001", max: answers_helper_residual(answer).to_f, step: "0.001", class: "form-control my-1" %>
  <% end %>

  <%= form.label :scheduled_at, class: "form-label m-1" %>
  <% if answer.present? && answer.scheduled_at.present? %>
    <%= form.date_field :scheduled_at, value: answer.scheduled_at.to_date, class: 'form-control my-1'%>
  <% else %>
    <%= form.date_field :scheduled_at, value: answer.order.desired_on.to_date, class: 'form-control my-1'%>
  <% end %>

  <div class="d-grid gap-2">
    <%= form.submit yield(:btn_text), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<% provide(:title, "回答情報編集") %>
<% provide(:btn_text, '更新') %>

<div class="text-center">
  <h1>回答情報編集</h1>
</div>

<div class="row justify-content-center">
  <div class="col-3">
    <h3>発注情報</h3>
    <p class="fw-bold"><%= "発注量トータル : #{@total}" %></p>
    
    <p><%= "#{Order.human_attribute_name("order_on")} : #{@answer.order.order_on.strftime("%Y / %m / %d")}" %></p>
    <p class="fw-bold"><%= "#{Order.human_attribute_name("paint")} : #{@answer.order.paint.name}" %></p>
    <p><%= "#{Order.human_attribute_name("quantity")} : #{@answer.order.quantity}" %></p>
    <p class="fw-bold"><%= "残量[kg] : #{answers_helper_residual(@answer)}" %></p>
    <p class="fw-bold"><%= "#{Order.human_attribute_name("desired_on")} : #{@answer.order.desired_on.strftime("%Y / %m / %d")}" %></p>
    <p><%= "#{Order.human_attribute_name("note")} : #{@answer.order.note.present? ? @answer.order.note : "-"}" %></p>
  </div>
  <div class="col-5">
    <%= render "form",  order: nil, answer: @answer %>
  </div>
</div>

app/views/answers/index.html.erb
<% provide(:title, "回答一覧") %>
<div class="text-center my-3">
  <h1><%= answer_title(@order) %></h1>
</div>
<div class="row justify-content-center text-center">
  <div class="col-12">
      <% if @order.present? %>
        <h3>発注情報</h3>
        <td><%= link_to "編集", edit_order_path(@order), class: "btn btn-sm btn-success" %></td>
        <td><%= link_to "削除", order_path(@order), data: {turbo_method: :delete,
                                                          turbo_confirm: "本当に削除しますか？"
                                                        }, class: "btn btn-sm btn-danger" %></td>
        <table class="table my-3">
          <thead>
            <tr>
              <th scope="col">発注<%= Order.human_attribute_name("id") %></th>
              <th scope="col"><%= Order.human_attribute_name("paint") %></th>
              <th scope="col"><%= Order.human_attribute_name("order_on") %></th>
              <th scope="col"><%= Order.human_attribute_name("desired_on") %></th>
              <th scope="col"><%= Order.human_attribute_name("quantity") %></th>
              <th scope="col"><%= Order.human_attribute_name("note") %></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @order.id %></td>
              <td><%= @order.paint.name %></td>
              <td><%= @order.order_on.strftime("%Y / %m / %d") %></td>
              <td><%= @order.desired_on.strftime("%Y / %m / %d") %></td>
              <td><%= @order.quantity %></td>
              <td><%= @order.note %></td>
            </tr>
          </tbody>
        <table>
        <h3>回答一覧</h3>
        <% if orders_helper_residual(@order).to_i != 0 %>
          <td><%= link_to "新規回答登録", new_order_answer_path(@order), class: "btn btn-sm btn-primary" %></td>
        <% else %>
          <td><%= link_to "新規回答できません", new_order_answer_path(@order), class: "btn btn-sm btn-primary disabled" %></td>
        <% end %>
      <% end %>

      <% if @answers.present? %>
        <table id ="fav-table" class="table my-3">
          <thead>
            <tr>
              <th scope="col"><%= Answer.human_attribute_name("order.paint") %></th>
              <th scope="col"><%= Answer.human_attribute_name("scheduled_at") %></th>
              <th scope="col"><%= Answer.human_attribute_name("quantity") %></th>
              <th scope="col">残量[kg]</th>
              <th scope="col"><%= Answer.human_attribute_name("note") %></th>
            </tr>
          </thead>
          <tbody>
            <% @answers.each do |answer| %>
                <tr class="align-middle">
                  <td><%= answer.order.paint.name %></td>
                  <td><%= answer.scheduled_at.strftime("%Y / %m / %d") %></td>
                  <td><%= answer.quantity %></td>
                  <td><%= answers_helper_residual(answer) %></td>
                  <td><%= answer.note %></td>
                  <td><%= link_to "編集", edit_answer_path(answer), class: "btn btn-sm btn-success" %></td>
                  <td><%= link_to "削除", answer_path(answer), data: {turbo_method: :delete,
                                                                      turbo_confirm: "本当に削除しますか？"
                                                                      }, class: "btn btn-sm btn-danger" %></td>
                </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
  </div>
</div>

app/views/answers/new.html.erb
<% provide(:title, "回答登録") %>
<% provide(:btn_text, '新規登録') %>

<div class="text-center">
  <h1>回答登録</h1>
</div>

<div class="row justify-content-center">
  <div class="col-3">
    <h3>発注情報</h3>
    <p class="fw-bold"><%= "発注量トータル : #{@total}" %></p>
    
    <p><%= "#{Order.human_attribute_name("order_on")} : #{@order.order_on.strftime("%Y / %m / %d")}" %></p>
    <p class="fw-bold"><%= "#{Order.human_attribute_name("paint")} : #{@order.paint.name}" %></p>
    <p><%= "#{Order.human_attribute_name("quantity")} : #{@order.quantity}" %></p>
    <p class="fw-bold"><%= "残量[kg] : #{answers_helper_residual(@answer)}" %></p>
    <p class="fw-bold"><%= "#{Order.human_attribute_name("desired_on")} : #{@order.desired_on.strftime("%Y / %m / %d")}" %></p>
    <p><%= "#{Order.human_attribute_name("note")} : #{@order.note.present? ? @order.note : "-"}" %></p>
  </div>
  <div class="col-5">
    <%= render "form", order: @order , answer: @answer %>
  </div>
</div>

app/views/answers/show.html.erb
<h1>Answers#show</h1>
<p>Find me in app/views/answers/show.html.erb</p>