config/routes.rb
Rails.application.routes.draw do
  get 'arrivals/index_all', to: 'arrivals#index_all'
  get 'answers/index'
  get 'answers/show'
  get 'answers/new'
  get 'answers/edit'
  root 'sessions#new'

  # LINEログイン
  get 'line_login_api/login', to: 'line_login_api#login'
  get 'line_login_api/callback', to: 'line_login_api#callback'
  
  # ログイン機能
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :users
  resources :departments
  resources :manufacturers
  resources :suppliers
  resources :paints
  resources :orders, shallow: true do
    resources :answers # :shallowオプションを使うことで、ルーティングの記述を複雑にせず、かつ深いネストを作らない。
    resources :arrivals
  end
  resources :inventories
  resources :all_inventories
  resources :withdraws
  resources :stocks, only: [:index, :show]
end

app/models/all_inventory.rb
class AllInventory < ApplicationRecord
  belongs_to :paint
  with_options presence: true do
    validates :paint_id
    validates :inventory_at
  end
  # 塗料棚卸を登録する際、その塗料、年月の組み合わせが一意であること。
  validates :paint_id, uniqueness: {scope: [:inventory_at]}
  validate :no_future_registration_possible
  
  def no_future_registration_possible
    if inventory_at >= Date.current.beginning_of_month
      errors.add('今月以降の棚卸は確定できません。')
    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  # include AnswersHelper
  belongs_to :order, class_name: 'Order',foreign_key: 'order_id'
end

app/models/arrival.rb
class Arrival < ApplicationRecord
  belongs_to :order
  belongs_to :user
  with_options presence: true do
    validates :order_id
    validates :user_id
    validates :arrival_at
    validates :quantity
  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :users
  has_many :inventorys
  has_many :withdraws, foreign_key: "reference_id"
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  belongs_to :editor, class_name: "User", foreign_key: "editor_id"
  belongs_to :department
  belongs_to :paint
    with_options presence: true do
    validates :inventory_at
    validates :quantity
  end
  # 塗料棚卸を登録する際、その塗料、部署、年月の組み合わせが一意であること。
  validates :paint_id, uniqueness: {scope: [:department_id, :inventory_at]}
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :paint
  belongs_to :user
  belongs_to :registerer, class_name: "User", foreign_key: "registerer_id"
  belongs_to :editor, class_name: "User", foreign_key: "editor_id"
  has_many :answers, dependent: :destroy
  has_many :arrivals, dependent: :destroy
  with_options presence: true do
    validates :paint_id
    validates :user_id
    validates :order_on
    validates :quantity
  end
end

app/models/paint.rb
class Paint < ApplicationRecord
  belongs_to :manufacturer
  has_many :orders, dependent: :destroy
  has_many :inventories
  has_many :all_inventories
  has_many :withdraws, foreign_key: "reference_id"
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :department, foreign_key: "department_id", optional: true
  has_many :orders, foreign_key: "reference_id"
  has_many :orders, foreign_key: "registerer_id"
  has_many :orders, foreign_key: "editor_id"
  has_many :arrivals, foreign_key: "arrival_id"
  has_many :inventorys, foreign_key: "reference_id"
  has_many :inventorys, foreign_key: "editor_id"
  has_many :withdraws, foreign_key: "reference_id"
  with_options presence: true do
    validates :name
    validates :department_id
  end
  has_secure_password
  validates :password, presence: true, length: { minimum: 4 }, allow_nil: true
end

app/models/withdraw.rb
class Withdraw < ApplicationRecord
  belongs_to :user
  belongs_to :department
  belongs_to :paint
end

app/helpers/answers_helper.rb
module AnswersHelper

# 納入予定量回答の総量に対しての注文残量[kg]
  def answers_helper_residual(answer)
    answers = answer.order.answers
    answers_total_quantity = 0
    answers.each do |ans|
      answers_total_quantity += ans.quantity if ans.quantity.present?
    end
    if answers_total_quantity == 0
      return answer.order.quantity
    else
      return answer.order.quantity - answers_total_quantity
    end
  end

  def answer_title(order)
    base_title = "回答一覧"
    if order.nil?
      base_title
    else
      "発注に対する" + base_title
    end
  end
end

app/helpers/arrivals_helper.rb
module ArrivalsHelper
  
  # 入荷量の総量に対しての注文残量[kg]
  def arrivals_helper_residual(order)
    arrivals = order.arrivals
    arrivals_total_quantity = 0
    if arrivals.nil?
      arrivals_total_quantity
    else
      arrivals.each do |arri|
        arrivals_total_quantity += arri.quantity if arri.quantity.present?
      end
    end
    order.quantity - arrivals_total_quantity
  end
end

app/helpers/orders_helper.rb
module OrdersHelper

  # 納入予定量回答の総量に対しての注文残量[kg]
  def orders_helper_residual(order)
    answers = order.answers
    answers_total_quantity = 0
    if answers.nil?
      answers_total_quantity
    else
      answers.each do |ans|
        answers_total_quantity += ans.quantity if ans.quantity.present?
      end
      order.quantity - answers_total_quantity
    end
  end

end

app/helpers/paints_helper.rb
module PaintsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 引数に渡されたユーザーオブジェクトでログインします。
  def log_in(user)
    session[:user_id] = user.id
  end

  # セッションと@current_userを破棄します
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # 現在ログイン中のユーザーがいる場合オブジェクトを返します。
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # 現在ログイン中のユーザーがいればtrue、そうでなければfalseを返します。
  def logged_in?
    !current_user.nil?
  end

end

app/helpers/stocks_helper.rb
module StocksHelper

  def beginning_stocks(paint)
    AllInventory.find_by(inventory_at: @last_month, paint_id: paint.id)
  end

  def monthly_withdraws_quantity(paint)
    @monthly_withdraws = Withdraw.where(withdraw_at: @first_day..@day, paint_id: paint.id)
    @withdraws_quantity = 0
    @monthly_withdraws.each do |withdraw|
      @withdraws_quantity += withdraw.quantity
    end
    return @withdraws_quantity
  end
  
  def monthly_arrivals_quantity(paint)
    @monthly_arrivals = Arrival.joins(:order).where(arrival_at: @first_day..@day).where(orders: {paint_id: paint.id})

    @arrivals_quantity = 0.0
    @monthly_arrivals.each do |arrival|
      @arrivals_quantity += arrival.quantity
    end
    return @arrivals_quantity
  end

  def stock(paint)
    beginning_stocks(paint).quantity + @arrivals_quantity - @withdraws_quantity
  end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/withdraws_helper.rb
module WithdrawsHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Stock Control App", "#", class: "fs-2 text-light text-decoration-none" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav align-items-center">
        <li class="nav-item">
          <%= link_to "", "#" %>
        </li>
        <li class="nav-item">
          <%= link_to "", "#" %>
        </li>
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              仕入
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to "発注登録", new_order_path, class: "dropdown-item" %></li>
              <li><%= link_to "発注一覧", orders_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "回答一覧", answers_index_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "入荷一覧", arrivals_index_all_path, class: "dropdown-item" %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              棚卸
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to "棚卸登録", new_inventory_path, class: "dropdown-item" %></li>
              <li><%= link_to "班別棚卸一覧", inventories_path, class: "dropdown-item" %></li>
              <li><%= link_to "棚卸まとめ一覧", all_inventories_path, class: "dropdown-item" %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              出庫
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to "出庫登録", new_withdraw_path, class: "dropdown-item" %></li>
              <li><%= link_to "出庫一覧", withdraws_path, class: "dropdown-item" %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              在庫
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to "在庫一覧", stocks_path, class: "dropdown-item" %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              マスタメンテナンス
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to "製造元", manufacturers_path, class: "dropdown-item" %></li>
              <li><%= link_to "仕入先", suppliers_path, class: "dropdown-item" %></li>
              <li><%= link_to "塗料", paints_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "ユーザー", users_path, class: "dropdown-item" %></li>
              <li><%= link_to "部署", departments_path, class: "dropdown-item" %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to "ユーザー情報", current_user, class: "dropdown-item" %></li>
              <li><%= link_to "ログアウト", logout_path, data: {
                      turbo_method: :delete,
                      turbo_confirm: "ログアウトしますか？"},class: "dropdown-item" if current_user %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render "layouts/shim" %>
    <%# bootstrapのアイコン付きのアラートを使用する %>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </symbol>
    </svg>
    <%# jQuery本体とtablesorterのjs、cssの読み込み %>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/js/jquery.tablesorter.min.js"></script>

    <%# 表のソートアイコン %>
    <style>
    .tablesorter-headerUnSorted {
        background-image:url("/images/sort-color.png");
        background-repeat: no-repeat;
        background-position: center right;
    }
    .tablesorter-headerAsc {
        background-image:url("/images/sort-a-color.png");

        background-repeat: no-repeat;
        background-position: center right;
        border-bottom: #000 2px solid;
    }
    .tablesorter-headerDesc {
        background-image:url("/images/sort-d-color.png");

        background-repeat: no-repeat;
        background-position: center right;
        border-bottom: #000 2px solid;
    }
    .sorter-false {
        background-image: none;
    }

    /* LINEログイン用のボタン色 */
    .btn-line {
      color: #fff;
      background-color: #06C755;
      border: none;
    }

    /* LINEログインボタンのマウスオーバー時 */
    .btn-line:hover {
        color: #fff;
        content: '';
        background-color: #05B749;
        cursor: pointer;
    }
    </style>
    <script> 
      // tablesorterの導入　ソートの実行
      $(document).ready(function() {
        $('#fav-table').tablesorter();
      });
    </script> 

  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container mt-2">
      <% flash.each do |message_type, msg| %>
        <%# .html_safe はbootstrapのflashで改行可能にする %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
    </div>
    <div class="container bg-light mt-4 rounded">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %><br>
      beginning_of_month<%= @beginning_of_month if @beginning_of_month.present? %><br>
      first_day<%= @first_day if @first_day.present? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= "入力エラーが#{@user.errors.count}個あります。" %>.
    </div>
    <ul class="text-danger">
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_of_arrivals.html.erb
<% if @arrival.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= "入力エラーが#{@arrival.errors.count}個あります。" %>.
    </div>
    <ul class="text-danger">
    <% @arrival.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_of_departments.html.erb
<% if @department.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= "入力エラーが#{@department.errors.count}個あります。" %>.
    </div>
    <ul class="text-danger">
    <% @department.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_of_inventories.html.erb
<% if @inventory.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= "入力エラーが#{@inventory.errors.count}個あります。" %>.
    </div>
    <ul class="text-danger">
    <% @inventory.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_of_manufacturers.html.erb
<% if @manufacturer.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= "入力エラーが#{@manufacturer.errors.count}個あります。" %>.
    </div>
    <ul class="text-danger">
    <% @manufacturer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_of_orders.html.erb
<% if @order.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= "入力エラーが#{@order.errors.count}個あります。" %>.
    </div>
    <ul class="text-danger">
    <% @order.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_of_paints.html.erb
<% if @paint.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= "入力エラーが#{@paint.errors.count}個あります。" %>.
    </div>
    <ul class="text-danger">
    <% @paint.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_of_suppliers.html.erb
<% if @supplier.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= "入力エラーが#{@supplier.errors.count}個あります。" %>.
    </div>
    <ul class="text-danger">
    <% @supplier.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>